import { NextResponse } from 'next/server'
import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } from 'docx'
import PDFDocument from 'pdfkit'

// Simple markdown-to-structured-content parser
function parseMarkdownContent(markdown) {
    const lines = markdown.split('\n')
    const elements = []

    lines.forEach(line => {
        const trimmed = line.trim()
        if (!trimmed) {
            elements.push({ type: 'blank' })
        } else if (trimmed.startsWith('# ')) {
            elements.push({ type: 'h1', text: trimmed.replace(/^# /, '') })
        } else if (trimmed.startsWith('## ')) {
            elements.push({ type: 'h2', text: trimmed.replace(/^## /, '') })
        } else if (trimmed.startsWith('### ')) {
            elements.push({ type: 'h3', text: trimmed.replace(/^### /, '') })
        } else if (trimmed.startsWith('- ') || trimmed.startsWith('* ')) {
            elements.push({ type: 'bullet', text: trimmed.replace(/^[-*] /, '') })
        } else if (/^\d+\.\s/.test(trimmed)) {
            elements.push({ type: 'numbered', text: trimmed.replace(/^\d+\.\s/, '') })
        } else {
            elements.push({ type: 'paragraph', text: trimmed })
        }
    })

    return elements
}

// Strip markdown bold/italic markers for plain text
function stripMarkdown(text) {
    return text
        .replace(/\*\*\*(.*?)\*\*\*/g, '$1')
        .replace(/\*\*(.*?)\*\*/g, '$1')
        .replace(/\*(.*?)\*/g, '$1')
        .replace(/__(.*?)__/g, '$1')
        .replace(/_(.*?)_/g, '$1')
        .replace(/`(.*?)`/g, '$1')
}

// Parse text runs with bold/italic
function parseTextRuns(text) {
    const runs = []
    const regex = /\*\*(.*?)\*\*/g
    let lastIndex = 0
    let match

    while ((match = regex.exec(text)) !== null) {
        if (match.index > lastIndex) {
            runs.push(new TextRun({ text: text.slice(lastIndex, match.index), size: 22 }))
        }
        runs.push(new TextRun({ text: match[1], bold: true, size: 22 }))
        lastIndex = regex.lastIndex
    }

    if (lastIndex < text.length) {
        runs.push(new TextRun({ text: text.slice(lastIndex), size: 22 }))
    }

    return runs.length > 0 ? runs : [new TextRun({ text, size: 22 })]
}

// --- DOCX Generation ---
async function generateDocx(title, markdownContent) {
    const elements = parseMarkdownContent(markdownContent)
    const paragraphs = []

    // Title
    paragraphs.push(
        new Paragraph({
            children: [new TextRun({ text: title, bold: true, size: 32, font: 'Calibri' })],
            alignment: AlignmentType.CENTER,
            spacing: { after: 200 },
        })
    )

    // Subtitle line
    paragraphs.push(
        new Paragraph({
            children: [new TextRun({ text: `Generated by Lantaw AI — FloodWatch Platform`, italics: true, size: 18, color: '888888' })],
            alignment: AlignmentType.CENTER,
            spacing: { after: 400 },
        })
    )

    elements.forEach(el => {
        if (el.type === 'blank') {
            paragraphs.push(new Paragraph({ spacing: { after: 100 } }))
        } else if (el.type === 'h1') {
            paragraphs.push(new Paragraph({
                children: [new TextRun({ text: stripMarkdown(el.text), bold: true, size: 28 })],
                heading: HeadingLevel.HEADING_1,
                spacing: { before: 300, after: 150 },
            }))
        } else if (el.type === 'h2') {
            paragraphs.push(new Paragraph({
                children: [new TextRun({ text: stripMarkdown(el.text), bold: true, size: 24 })],
                heading: HeadingLevel.HEADING_2,
                spacing: { before: 250, after: 100 },
            }))
        } else if (el.type === 'h3') {
            paragraphs.push(new Paragraph({
                children: [new TextRun({ text: stripMarkdown(el.text), bold: true, size: 22 })],
                heading: HeadingLevel.HEADING_3,
                spacing: { before: 200, after: 80 },
            }))
        } else if (el.type === 'bullet') {
            paragraphs.push(new Paragraph({
                children: parseTextRuns(el.text),
                bullet: { level: 0 },
                spacing: { after: 60 },
            }))
        } else if (el.type === 'numbered') {
            paragraphs.push(new Paragraph({
                children: parseTextRuns(el.text),
                numbering: { reference: 'default-numbering', level: 0 },
                spacing: { after: 60 },
            }))
        } else {
            paragraphs.push(new Paragraph({
                children: parseTextRuns(el.text),
                spacing: { after: 100 },
            }))
        }
    })

    const doc = new Document({
        numbering: {
            config: [{
                reference: 'default-numbering',
                levels: [{
                    level: 0,
                    format: 'decimal',
                    text: '%1.',
                    alignment: AlignmentType.START,
                }],
            }],
        },
        sections: [{
            properties: {
                page: {
                    margin: { top: 1440, bottom: 1440, left: 1440, right: 1440 },
                },
            },
            children: paragraphs,
        }],
    })

    const buffer = await Packer.toBuffer(doc)
    return buffer
}

// --- PDF Generation ---
async function generatePdf(title, markdownContent) {
    return new Promise((resolve, reject) => {
        try {
            const doc = new PDFDocument({
                size: 'A4',
                margins: { top: 72, bottom: 72, left: 72, right: 72 },
            })

            const chunks = []
            doc.on('data', chunk => chunks.push(chunk))
            doc.on('end', () => resolve(Buffer.concat(chunks)))
            doc.on('error', reject)

            // Title
            doc.fontSize(20).font('Helvetica-Bold').text(title, { align: 'center' })
            doc.moveDown(0.3)
            doc.fontSize(9).font('Helvetica-Oblique').fillColor('#888888')
                .text('Generated by Lantaw AI — FloodWatch Platform', { align: 'center' })
            doc.fillColor('#000000')
            doc.moveDown(1.5)

            // Horizontal rule
            doc.moveTo(72, doc.y).lineTo(523, doc.y).stroke('#dddddd')
            doc.moveDown(0.8)

            const elements = parseMarkdownContent(markdownContent)

            elements.forEach(el => {
                // Check page overflow
                if (doc.y > 700) {
                    doc.addPage()
                }

                if (el.type === 'blank') {
                    doc.moveDown(0.4)
                } else if (el.type === 'h1') {
                    doc.moveDown(0.5)
                    doc.fontSize(16).font('Helvetica-Bold').text(stripMarkdown(el.text))
                    doc.moveDown(0.3)
                } else if (el.type === 'h2') {
                    doc.moveDown(0.4)
                    doc.fontSize(13).font('Helvetica-Bold').text(stripMarkdown(el.text))
                    doc.moveDown(0.2)
                } else if (el.type === 'h3') {
                    doc.moveDown(0.3)
                    doc.fontSize(11).font('Helvetica-Bold').text(stripMarkdown(el.text))
                    doc.moveDown(0.15)
                } else if (el.type === 'bullet') {
                    doc.fontSize(10).font('Helvetica').text(`  •  ${stripMarkdown(el.text)}`, { indent: 20 })
                    doc.moveDown(0.1)
                } else if (el.type === 'numbered') {
                    doc.fontSize(10).font('Helvetica').text(`     ${stripMarkdown(el.text)}`, { indent: 20 })
                    doc.moveDown(0.1)
                } else {
                    doc.fontSize(10).font('Helvetica').text(stripMarkdown(el.text), { lineGap: 3 })
                    doc.moveDown(0.2)
                }
            })

            // Footer
            doc.moveDown(2)
            doc.moveTo(72, doc.y).lineTo(523, doc.y).stroke('#dddddd')
            doc.moveDown(0.3)
            doc.fontSize(8).font('Helvetica-Oblique').fillColor('#999999')
                .text(`FloodWatch Platform — Lantaw AI Document — ${new Date().toLocaleDateString()}`, { align: 'center' })

            doc.end()
        } catch (err) {
            reject(err)
        }
    })
}

// --- Main API Route Handler ---
export async function POST(request) {
    try {
        const { title, content, format } = await request.json()

        if (!content || !title) {
            return NextResponse.json({ error: "Missing title or content." }, { status: 400 })
        }

        const fileFormat = (format || 'pdf').toLowerCase()
        if (fileFormat !== 'docx' && fileFormat !== 'pdf') {
            return NextResponse.json({ error: "Only 'docx' and 'pdf' formats are supported." }, { status: 400 })
        }

        let buffer
        let contentType
        let extension

        if (fileFormat === 'docx') {
            buffer = await generateDocx(title, content)
            contentType = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
            extension = 'docx'
        } else {
            buffer = await generatePdf(title, content)
            contentType = 'application/pdf'
            extension = 'pdf'
        }

        const safeTitle = title.replace(/[^a-zA-Z0-9-_ ]/g, '').replace(/\s+/g, '_').substring(0, 60)
        const fileName = `${safeTitle}_Lantaw.${extension}`

        return new NextResponse(buffer, {
            status: 200,
            headers: {
                'Content-Type': contentType,
                'Content-Disposition': `attachment; filename="${fileName}"`,
            }
        })
    } catch (err) {
        console.error("Document generation error:", err)
        return NextResponse.json({ error: "Failed to generate document." }, { status: 500 })
    }
}
