class LantawFileStructurePlan:
    """
    Utility class defining the content structure and security guardrails 
    for any files (documents or spreadsheets) generated by Lantaw AI.
    
    This ensures that when a user requests a file, the AI structures the 
    content concisely and strictly excludes any sensitive personal data.
    """

    @staticmethod
    def get_file_content_guardrails() -> str:
        """
        Returns the set of rules dictating how file content should be structured 
        and what data must be excluded for security reasons.
        """
        return (
            "\n\n--- FILE CONTENT & SECURITY GUARDRAILS ---\n"
            "If you are generating a document or a spreadsheet, you MUST adhere to the following rules regarding its content:\n"
            "1. CONCISENESS: The content must be highly concise, professional, and straight to the point. Avoid fluff, long-winded introductions, or unnecessary conversational filler.\n"
            "2. NO SENSITIVE DATA OR RAW IDs: You must STRICTLY EXCLUDE any Personally Identifiable Information (PII) or sensitive data. Additionally, NEVER output raw database IDs, system UUIDs, or long alphanumeric hashes (e.g. 'cafaab15-5574...', '085d2ff5...'). Replace them with generic sequential names (e.g., 'Station 1', 'Location A') or omit the ID completely and just use the known place name.\n"
            "3. STRUCTURAL CLARITY: Ensure the data is logically organized. If it's a document, use clear headings and bullet points. If it's a spreadsheet, ensure the chosen source table accurately represents the user's request without exposing protected columns.\n"
        )
